### ISSUE TITLE
build-wanted-system-message

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#11]
On attempting to send an encrypted message to the reviewers group I got an error.  

The Code I used 1st attempt:
{
  "walletName": "SamSept30no3",
  "walletPassword": "password",
  "accountName": "account 2",
  "payerAddress": "TZ9UduhyK7Cq1uEga1nTh4i5mHjSmLDy22",
  "destinationAddress": "2N7uXzz7PCLZzaCAaE4gRUzUJFUVgX2ERdS",
  "message": "To the moon!",
  "encryptMessage": true
}

My Response Body from 1st attempt:
Code 400 Undocutmented Error:  Bad Request
{
  "errors": [
    {
      "status": 400,
      "message": "Index was outside the bounds of the array.",
      "description": "System.IndexOutOfRangeException: Index was outside the bounds of the array.\n   at NBitcoin.Crypto.RsaPrivateKey.FromHex(String hexString) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\NBitcoin\\Crypto\\RsaPrivateKey.cs:line 38\n   at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.AddMessage(TransactionBuildContext context) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\WalletTransactionHandler.Messaging.cs:line 40\n   at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.BuildWantedSystemMessage(TransactionBuildContext context) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\WalletTransactionHandler.Messaging.cs:line 52\n   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.BuildWantedSystemMessage(BuildWantedSystemMessageRequest request) in C:\\Work\\TopTal-Aequitas\\AequitasFullNode\\src\\Stratis.Bitcoin.Features.Wallet\\Controllers\\WalletController.Messaging.cs:line 143"
    }
  ]
}

The Code I used 2nd attempt:
##the only thing i changed was changing true to True
{
  "walletName": "SamSept30no3",
  "walletPassword": "password",
  "accountName": "account 2",
  "payerAddress": "TZ9UduhyK7Cq1uEga1nTh4i5mHjSmLDy22",
  "destinationAddress": "2N7uXzz7PCLZzaCAaE4gRUzUJFUVgX2ERdS",
  "message": "To the moon!",
  "encryptMessage": True
}

Response body 2nd attempt:
Code 500 Undocumented Error: Internal Server Error

 content-length: 0 
 date: Mon, 08 Oct 2018 03:55:32 GMT 
 server: Kestrel

**Comment by andrasfuchs** [comment]
Nice find! It's a kind of tricky. I added some extra verification to the message builder, I hope it fixes the problem.
As you can also see the testing gets more and more complicated as we go forward. Interestingly it worked on my local node (that's why I didn't find this one earlier), and I could not fully reproduce the problem on our public node, it seems to be working now.

On the other hand, I felt that it's important to extend a the testing documentation a little for the build-wanted-system-message command, and I also added more details to the error message.

If you need to use true/false values in the requests they should always be lowercase, the uppercase True is not recognized by the low level method we have to use. (And since it's low level, I can't add a more descriptive error message there.)

Let me know if it works. 

I'll continue testing now to make sure that you guys don't get stuck at the next few steps.
