### ISSUE TITLE
400 Error on watch-and-rescan

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#6]
On #5: Do a rescan if the transaction missed by the node.aequitascoin.com
/api/WatchOnlyWallet/watch-and-rescan

I got an unexpected response:
400 Error:  Bad Request

I tried both my addresses and different times but it kept throwing the 400 Error:  Bad Request regardless of my input.

This was on my group address:
2N3DBZDE6mpdPrepTodRVBTeyL4m86f8fj7 

And the wallet that initiated the transaction:
TDnx5wRXyQ5wXq1wC5kg4rwtdWw9542eo6

For the time field I used both the sample date/time and the current date/time.

**Comment by andrasfuchs** [comment]
The bug is fixed, it was related to an HTTP error code formatting procedure.

Now, just after executing the API function, you should get back something similar to this:
_{
  "isInProgress": true,
  "fromTime": 1535752800,
  "untilTime": 1538124672,
  "progressPercentage": 0
}_

If you wait a few seconds and re-execute the same API function with the same parameters, the progressPercentage should change, like this:

_{
  "isInProgress": true,
  "fromTime": 1535752800,
  "untilTime": 1538124672,
  "progressPercentage": 55.47078425817244
}_

Depending on the blockchain size and the date we should rescan the blocks this procedure can take a while, but thanks to this method you can always request the node how much work is still left.
