### ISSUE TITLE
build transaction error

### ISSUE THREAD

**Issue by ghost** [AequitasCoinProject/AequitasFullNode#7]
Using last weeks group and addresses I tried to build the transaction several times but every time it returned an error.  

attempt 1:
{
  "feeAmount": "0.001",
  "password": "password",
  "walletName": "SamSept19no2",
  "accountName": "account 1",
  "destinationAddress": "2N3DBZDE6mpdPrepTodRVBTeyL4m86f8fj7",
  "amount": "0.25",
  "feeType": "Low",
  "allowUnconfirmed": true,
  "shuffleOutputs": true
}

response 1:
"message": "No amount specified."

attempt 2:
{
  "feeAmount": "0.001",
  "password": "password",
  "walletName": "SamSept19no2",
  "accountName": "account 1",
  "destinationAddress": "2N3DBZDE6mpdPrepTodRVBTeyL4m86f8fj7",
  "amount": "1.25",
  "feeType": "Low",
  "allowUnconfirmed": true,
  "shuffleOutputs": true
}

response 2:
"message": "Could not build the transaction. Details: Fee of 0.00000001 is too low. The policy minimum is 0.00001960."

attempt 3:
{
  "feeAmount": "0.5",
  "password": "password",
  "walletName": "SamSept19no2",
  "accountName": "account 1",
  "destinationAddress": "2N3DBZDE6mpdPrepTodRVBTeyL4m86f8fj7",
  "amount": "1.25",
  "feeType": "Low",
  "allowUnconfirmed": true,
  "shuffleOutputs": true
}

response 3:
"message": "Could not build the transaction. Details: Fee of 0.00000001 is too low. The policy minimum is 0.00001960."

**Comment by andrasfuchs** [comment]
The problem here is that you didn't define the feeAmount and amount values in atomic units.
Atomic units are the smallest possible units on a given network. 
On Bitcoin it's the Satoshi, on Stratis Test it's called "s-test" now.
As soon as we define our own currency and it's atomic unit this will work in a way that you can define money amounts in a format like "0.32 AEQ" or similar.
Until that point the system expects us to set them as integers, meaning the number of atomic units. 
So, in the example above the fee amount should be 100000 and the amount 25000000.

I updated the testing instructions a few weeks ago because of this, but I didn't mark it and didn't mention it to you, sorry about that. Also the error message isn't useful, I had to investigate the issue as well, it's not obvious at all what's wrong with the request.

You can try again with the following format:
_/api/Wallet/build-transaction
{
"feeAmount": "100000",
"password": "password",
"walletName": "SamSept19no2",
"accountName": "account 1",
"destinationAddress": "2N3DBZDE6mpdPrepTodRVBTeyL4m86f8fj7",
"amount": "25000000",
"feeType": "Low",
"allowUnconfirmed": true,
"shuffleOutputs": true
}_

**Comment by ghost** [comment]
I'm sorry, I accidentally opened the older set of instructions, leading to the copy paste error.  I recall you had changed it.
